### ISSUE TITLE
SLAM for L515

### ISSUE THREAD

**Issue by sai2602** [TIERS/tiers-lidars-dataset-enhanced#3]
Dear Team,

Thank you for the great work. The code handles avia, horizon, velodyne and ouster, but I would like to work with the L515 sensor. May I know how the handler for L515 data works and how the feature extraction from the L515 poincloud is done?

**Comment by Hasar12138** [comment]
sorry to reply you so late. This github repository is about the multi-lidar dataset, so I'm sorry that I can not  give you a specific answer for your question. But we test some SLAM algorithms using the L515 sensor on our data set, such as SSL-SLAM; due to the poor result, we finally did not Upload the corresponding results. If you are interested in the result, I can send it to you by email.
Regarding your question, maybe you can find the answer here [https://github.com/wh200720041/ssl_slam]

**Comment by sai2602** [comment]
Thank you for the update and sorry for the deay. I was not available for the last 7-8 days. I already tried the ssl_slam but the results were not great. Can you please share the code to me via email so that I can integrate it with other approaches and verify if the results are better? 
Email: saiparimi.lp@gmail.com

**Comment by Hasar12138** [comment]
Hi!
&nbsp; &nbsp; We did not make any improvements to ssl_slam, but just tested its performance. You said that the effect of ssl_slam is relatively poor. I think it is because ssl_slam uses only lidar data instead of integrating data such as IMU, which causes the device to drifts too much while spinning.
&nbsp; &nbsp; I think you should try ssl_slam3 [https://github.com/wh200720041/ssl_slam3], which is an improved version of ssl_slam that combines LiDAR and IMU data. Hope this helps you!
&nbsp; &nbsp;&nbsp;If you have further questions, please email ***@***.***.




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Friday, Dec 9, 2022 9:20 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [TIERS/tiers-lidars-dataset-enhanced] SLAM for L515 (Issue #3)





 
Thank you for the update and sorry for the deay. I was not available for the last 7-8 days. I already tried the ssl_slam but the results were not great. Can you please share the code to me via email so that I can integrate it with other approaches and verify if the results are better?
 Email: ***@***.***

**Comment by Hasar12138** [comment]
We did not make any improvements to ssl_slam, but just tested its performance. You said that the effect of ssl_slam is relatively poor. I think it is because ssl_slam uses only lidar data instead of integrating data such as IMU, which causes the device to drifts too much while spinning.
I think you should try ssl_slam3 [https://github.com/wh200720041/ssl_slam3], which is an improved version of ssl_slam that combines LiDAR and IMU data. Hope this helps you!
